require:
  - rubocop-rspec

AllCops:
  Exclude:
    - .bundle/**/*
    - db/migrate/**/*
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
  TargetRubyVersion: 2.6.5

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/swagger_helper.rb
    - spec/integration/**/*
    - spec/controllers/**/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/migrate/**/*

Layout/LineLength:
  Max: 200

RSpec/EmptyExampleGroup:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*

RSpec/RepeatedExample:
  Exclude:
    - spec/controllers/**/*

RSpec/ScatteredSetup:
  Exclude:
    - spec/integration/**/*
