require 'capistrano'
require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails'
require "whenever/capistrano"
require 'capistrano/puma'
require 'capistrano/puma/monit'
require 'capistrano/sidekiq'
require 'capistrano/sidekiq/monit'

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.cap').each { |r| import r }
